# Generated by Django 4.2.4 on 2023-09-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='completo',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='create',
            new_name='criar',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='descrição',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='título',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='usuário',
        ),
    ]
